export const FETCH_BREED = "FETCH_BREED";
export const FETCH_BREED_DONE = "FETCH_BREED_DONE";
export const FETCH_BREED_ERROR = "FETCH_BREED_ERROR";

export const FETCH_BREED_IMAGE = "FETCH_BREED_IMAGE";
export const FETCH_BREED_IMAGE_DONE = "FETCH_BREED_IMAGE_DONE";
export const FETCH_BREED_IMAGE_ERROR = "FETCH_BREED_IMAGE_ERROR";
